[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

# Install both production and development dependencies
[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

# Prune dev dependencies after build to reduce image size
[phases.prune]
cmds = ["npm prune --omit=dev"]

[start]
cmd = "npm start"
