service: auxeira-backend

provider:
  name: aws
  runtime: provided
  region: us-east-1
  memorySize: 1024
  timeout: 30

functions:
  api:
    image: 
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/auxeira-backend:latest
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-deployment-bucket

resources:
  Resources:
    ECRRepository:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: auxeira-backend
        ImageScanningConfiguration:
          ScanOnPush: true
