service: auxeira-backend
frameworkVersion: ^3.0.0

provider:
  name: aws
  runtime: nodejs18.x  # ZIP package needs runtime specified
  region: us-east-1
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: production

functions:
  api:
    handler: src/server-simple.handler  # ZIP package needs handler
    layers:
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:auxeira-solana-layer:1
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

# Exclude heavy dependencies (they're in the layer)
package:
  patterns:
    - '!node_modules/@solana/**'
    - '!tests/**'
    - '!*.md'
    - '!.git/**'
