service: auxeira-backend
frameworkVersion: ^3.0.0

provider:
  name: aws
  runtime: provided
  region: us-east-1
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: production

functions:
  api:
    image: 
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/auxeira-backend:latest
    layers:
      # Reference the layer dynamically
      - arn:aws:lambda:${aws:region}:${aws:accountId}:layer:auxeira-solana-layer:1
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
