service: auxeira-backend
frameworkVersion: ^3.0.0

provider:
  name: aws
  runtime: provided
  region: us-east-1
  memorySize: 2048  # Increased for Solana operations
  timeout: 30
  environment:
    NODE_ENV: production
    # Add your environment variables here as needed
    # SOLANA_RPC_URL: ${env:SOLANA_RPC_URL, 'https://api.mainnet-beta.solana.com'}

functions:
  api:
    image: 
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/auxeira-backend:latest
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

# CloudFormation resources if needed
resources:
  Resources:
    # Add DynamoDB tables or other resources here if needed
    ApiLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Ref: ApiLambdaFunction
        Principal: apigateway.amazonaws.com
